import type { BlockMetricRow, CohortInfoRow, ConceptSummaryRow, HierarchyMetaRow } from "./types"

export function mapCohortInfoRow(row: BlockMetricRow): CohortInfoRow {
  return {
    cohortId: Number(row.cohortId),
    cohortName: (row.cohortName as string | null) ?? null,
    shortName: (row.shortName as string | null) ?? null,
    subsetParent: row.subsetParent == null ? null : Number(row.subsetParent),
    isSubset: Boolean(row.isSubset),
    subsetDefinitionId: row.subsetDefinitionId == null ? null : Number(row.subsetDefinitionId),
    cohortEntries: row.cohortEntries == null ? null : Number(row.cohortEntries),
    cohortSubjects: row.cohortSubjects == null ? null : Number(row.cohortSubjects),
    cohortUse: (row.cohortUse as string | null) ?? null,
  }
}

export function mapSummaryRow(row: BlockMetricRow): ConceptSummaryRow {
  return {
    rowKey: String(row.rowKey),
    conceptId: Number(row.conceptId),
    conceptName: (row.conceptName as string | null) ?? null,
    conceptCode: (row.conceptCode as string | null) ?? null,
    ancestorConceptIds: (row.ancestorConceptIds as string | null) ?? null,
    domainId: String(row.domainId),
    countMode: String(row.countMode),
    bestPValue: (row.bestPValue as number | null) ?? null,
    binaryCaseYes: (row.binaryCaseYes as number | null) ?? null,
    binaryControlYes: (row.binaryControlYes as number | null) ?? null,
    binaryTotalCases: (row.binaryTotalCases as number | null) ?? null,
    binaryTotalControls: (row.binaryTotalControls as number | null) ?? null,
    binaryPValue: (row.binaryPValue as number | null) ?? null,
    binaryEffectSize: (row.binaryEffectSize as number | null) ?? null,
    binarySmd: (row.binarySmd as number | null) ?? null,
    binaryTestName: (row.binaryTestName as string | null) ?? null,
    categoricalCaseYes: (row.categoricalCaseYes as number | null) ?? null,
    categoricalControlYes: (row.categoricalControlYes as number | null) ?? null,
    categoricalPValue: (row.categoricalPValue as number | null) ?? null,
    categoricalEffectSize: (row.categoricalEffectSize as number | null) ?? null,
    categoricalSmd: (row.categoricalSmd as number | null) ?? null,
    categoricalTestName: (row.categoricalTestName as string | null) ?? null,
    categoricalDistribution: (row.categoricalDistribution as string | null) ?? null,
    countsCaseCount: (row.countsCaseCount as number | null) ?? null,
    countsControlCount: (row.countsControlCount as number | null) ?? null,
    countsCaseMean: (row.countsCaseMean as number | null) ?? null,
    countsControlMean: (row.countsControlMean as number | null) ?? null,
    countsCaseSd: (row.countsCaseSd as number | null) ?? null,
    countsControlSd: (row.countsControlSd as number | null) ?? null,
    countsP10Case: (row.countsP10Case as number | null) ?? null,
    countsP25Case: (row.countsP25Case as number | null) ?? null,
    countsMedianCase: (row.countsMedianCase as number | null) ?? null,
    countsP75Case: (row.countsP75Case as number | null) ?? null,
    countsP90Case: (row.countsP90Case as number | null) ?? null,
    countsP10Control: (row.countsP10Control as number | null) ?? null,
    countsP25Control: (row.countsP25Control as number | null) ?? null,
    countsMedianControl: (row.countsMedianControl as number | null) ?? null,
    countsP75Control: (row.countsP75Control as number | null) ?? null,
    countsP90Control: (row.countsP90Control as number | null) ?? null,
    countsPValue: (row.countsPValue as number | null) ?? null,
    countsEffectSize: (row.countsEffectSize as number | null) ?? null,
    countsSmd: (row.countsSmd as number | null) ?? null,
    countsTestName: (row.countsTestName as string | null) ?? null,
    ageCaseCount: (row.ageCaseCount as number | null) ?? null,
    ageControlCount: (row.ageControlCount as number | null) ?? null,
    ageCaseMean: (row.ageCaseMean as number | null) ?? null,
    ageControlMean: (row.ageControlMean as number | null) ?? null,
    ageCaseSd: (row.ageCaseSd as number | null) ?? null,
    ageControlSd: (row.ageControlSd as number | null) ?? null,
    ageP10Case: (row.ageP10Case as number | null) ?? null,
    ageP25Case: (row.ageP25Case as number | null) ?? null,
    ageMedianCase: (row.ageMedianCase as number | null) ?? null,
    ageP75Case: (row.ageP75Case as number | null) ?? null,
    ageP90Case: (row.ageP90Case as number | null) ?? null,
    ageP10Control: (row.ageP10Control as number | null) ?? null,
    ageP25Control: (row.ageP25Control as number | null) ?? null,
    ageMedianControl: (row.ageMedianControl as number | null) ?? null,
    ageP75Control: (row.ageP75Control as number | null) ?? null,
    ageP90Control: (row.ageP90Control as number | null) ?? null,
    agePValue: (row.agePValue as number | null) ?? null,
    ageEffectSize: (row.ageEffectSize as number | null) ?? null,
    ageSmd: (row.ageSmd as number | null) ?? null,
    ageTestName: (row.ageTestName as string | null) ?? null,
    daysCaseCount: (row.daysCaseCount as number | null) ?? null,
    daysControlCount: (row.daysControlCount as number | null) ?? null,
    daysCaseMean: (row.daysCaseMean as number | null) ?? null,
    daysControlMean: (row.daysControlMean as number | null) ?? null,
    daysCaseSd: (row.daysCaseSd as number | null) ?? null,
    daysControlSd: (row.daysControlSd as number | null) ?? null,
    daysP10Case: (row.daysP10Case as number | null) ?? null,
    daysP25Case: (row.daysP25Case as number | null) ?? null,
    daysMedianCase: (row.daysMedianCase as number | null) ?? null,
    daysP75Case: (row.daysP75Case as number | null) ?? null,
    daysP90Case: (row.daysP90Case as number | null) ?? null,
    daysP10Control: (row.daysP10Control as number | null) ?? null,
    daysP25Control: (row.daysP25Control as number | null) ?? null,
    daysMedianControl: (row.daysMedianControl as number | null) ?? null,
    daysP75Control: (row.daysP75Control as number | null) ?? null,
    daysP90Control: (row.daysP90Control as number | null) ?? null,
    daysPValue: (row.daysPValue as number | null) ?? null,
    daysEffectSize: (row.daysEffectSize as number | null) ?? null,
    daysSmd: (row.daysSmd as number | null) ?? null,
    daysTestName: (row.daysTestName as string | null) ?? null,
    continuousCaseCount: (row.continuousCaseCount as number | null) ?? null,
    continuousControlCount: (row.continuousControlCount as number | null) ?? null,
    continuousCaseMean: (row.continuousCaseMean as number | null) ?? null,
    continuousControlMean: (row.continuousControlMean as number | null) ?? null,
    continuousCaseSd: (row.continuousCaseSd as number | null) ?? null,
    continuousControlSd: (row.continuousControlSd as number | null) ?? null,
    continuousP10Case: (row.continuousP10Case as number | null) ?? null,
    continuousP25Case: (row.continuousP25Case as number | null) ?? null,
    continuousMedianCase: (row.continuousMedianCase as number | null) ?? null,
    continuousP75Case: (row.continuousP75Case as number | null) ?? null,
    continuousP90Case: (row.continuousP90Case as number | null) ?? null,
    continuousP10Control: (row.continuousP10Control as number | null) ?? null,
    continuousP25Control: (row.continuousP25Control as number | null) ?? null,
    continuousMedianControl: (row.continuousMedianControl as number | null) ?? null,
    continuousP75Control: (row.continuousP75Control as number | null) ?? null,
    continuousP90Control: (row.continuousP90Control as number | null) ?? null,
    continuousPValue: (row.continuousPValue as number | null) ?? null,
    continuousEffectSize: (row.continuousEffectSize as number | null) ?? null,
    continuousSmd: (row.continuousSmd as number | null) ?? null,
    continuousTestName: (row.continuousTestName as string | null) ?? null,
    continuousUnit: (row.continuousUnit as string | null) ?? null,
    // Absent from the projection unless the AI review tables are present; `?? null` covers both
    // "no AI tables" and "concept the AI never scored".
    aiCategory: (row.aiCategory as string | null) ?? null,
    aiRationale: (row.aiRationale as string | null) ?? null,
  }
}

// Lean counterpart to mapSummaryRow for buildHeatmapQuery results. Only the columns the heatmap
// and scatter read; every other ConceptSummaryRow field stays undefined (all optional). The
// detail dialog (ConceptDetailDialog) is null-tolerant and focusRow upgrades the row from the
// table model, so the missing fields are safe.
export function mapHeatmapRow(row: BlockMetricRow): ConceptSummaryRow {
  return {
    rowKey: String(row.rowKey),
    conceptId: Number(row.conceptId),
    conceptName: (row.conceptName as string | null) ?? null,
    conceptCode: (row.conceptCode as string | null) ?? null,
    // Carried so DuckDbOverview can rebuild the parent→children hierarchy (buildHierarchyIndex).
    ancestorConceptIds: (row.ancestorConceptIds as string | null) ?? null,
    domainId: String(row.domainId),
    countMode: String(row.countMode),
    bestPValue: (row.bestPValue as number | null) ?? null,
    binaryPValue: (row.binaryPValue as number | null) ?? null,
    binaryEffectSize: (row.binaryEffectSize as number | null) ?? null,
    countsPValue: (row.countsPValue as number | null) ?? null,
    countsEffectSize: (row.countsEffectSize as number | null) ?? null,
    agePValue: (row.agePValue as number | null) ?? null,
    ageEffectSize: (row.ageEffectSize as number | null) ?? null,
    daysPValue: (row.daysPValue as number | null) ?? null,
    daysEffectSize: (row.daysEffectSize as number | null) ?? null,
    continuousPValue: (row.continuousPValue as number | null) ?? null,
    continuousEffectSize: (row.continuousEffectSize as number | null) ?? null,
    categoricalPValue: (row.categoricalPValue as number | null) ?? null,
    categoricalEffectSize: (row.categoricalEffectSize as number | null) ?? null,
  }
}

export function mapHierarchyMetaRow(row: BlockMetricRow): HierarchyMetaRow {
  return {
    rowKey: String(row.rowKey),
    conceptId: Number(row.conceptId),
    conceptName: (row.conceptName as string | null) ?? null,
    conceptCode: (row.conceptCode as string | null) ?? null,
    ancestorConceptIds: (row.ancestorConceptIds as string | null) ?? null,
    domainId: String(row.domainId),
    countMode: String(row.countMode),
  }
}
